language: c
compiler:
  - gcc
services:
 - mysql
before_script:
 - mysql -e "create database gst_test; SET PASSWORD FOR 'root'@'localhost' = PASSWORD('gst'); FLUSH PRIVILEGES;"
 - psql -c 'create database gst_test;' -U postgres
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install autotools-dev libreadline-dev libncurses-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-sound1.2-dev libsdl-ttf2.0-dev libexpat1-dev freeglut3-dev libgmp3-dev libgdbm-dev libgtk2.0-dev libpq-dev libsigsegv-dev libffi-dev zip libsqlite3-dev unzip pkg-config libltdl-dev chrpath gawk libgnutls-dev automake autoconf libtool texinfo texlive
script: autoreconf -vi && ./configure --enable-mysql-tests=root:gst:gst_test --enable-postgres-tests=postgres:no:gst_test && make && make check && make distcheck
